eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/accountDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  config:
    students-url: http://localhost:8222/api/v1/students
