eureka:
  client:
    register-with-eureka: true
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/courses/**

management:
  tracing:
    sampling:
      probability: 1.0
